Repository Memory-Orgel/OYCDesignSystem, pull requests merged in 2024-07, with the labels that each got.

#2 [Chore/#1] 풀 리퀘스트 템플릿 등록
  .github/pull_request_template.md
Labels: 📐 Chore

#4 [Feat/#3] textfield atom 디자인
  src/components/atoms/TextField/TextField.stories.tsx
  src/components/atoms/TextField/TextField.styles.ts
  src/components/atoms/TextField/TextField.tsx
  src/components/atoms/TextField/TextField.types.ts
  src/themes/themeBase.ts
Labels: ✨ Feat

#6 [Fix/#5] Theme 값 수정
  public/.gitkeep
  src/components/atoms/Button/Button.stories.tsx
  src/components/atoms/TextField/TextField.styles.ts
  src/components/atoms/TextField/TextField.tsx
  src/components/atoms/TextField/TextField.types.ts
  src/themes/lightTheme.ts
  src/themes/themeBase.ts
Labels: 🔧 Fix

#11 [Feat/#8] dropdown component design
  src/assets/icons/arrow.svg
  src/assets/icons/icons.d.ts
  src/components/molecules/Dropdown/Dropdown.mdx
  src/components/molecules/Dropdown/Dropdown.stories.tsx
  src/components/molecules/Dropdown/Dropdown.styles.ts
  src/components/molecules/Dropdown/Dropdown.tsx
  src/components/molecules/Dropdown/Dropdown.types.ts
  src/components/molecules/Dropdown/DropdownItem.tsx
  src/components/molecules/Dropdown/index.ts
  src/themes/lightTheme.ts
Labels: ✨ Feat

#10 [Feat/#7] Toggle atom 컴포넌트 디자인
  src/components/atoms/TextField/TextField.styles.ts
  src/components/atoms/Toggle/Toggle.mdx
  src/components/atoms/Toggle/Toggle.stories.tsx
  src/components/atoms/Toggle/Toggle.styles.ts
  src/components/atoms/Toggle/Toggle.tsx
  src/components/atoms/Toggle/Toggle.types.ts
Labels: ✨ Feat

#12 [Feat/#9] checkbox atom component design
  src/components/atoms/CheckBox/CheckBox.stories.tsx
  src/components/atoms/CheckBox/CheckBox.styles.ts
  src/components/atoms/CheckBox/CheckBox.tsx
  src/components/atoms/CheckBox/CheckBox.types.ts
Labels: ✨ Feat

#14 [Feat/#13] npm publish 설정
  .gitignore
  README.md
  babel.config.js
  package-lock.json
  package.json
  src/components/atoms/CheckBox/index.ts
  src/components/atoms/TextField/index.ts
  src/components/atoms/Toggle/index.ts
  src/components/index.ts
  src/components/molecules/Dropdown/DropdownItem.tsx
  src/index.ts
  tsconfig.json
Labels: ✨ Feat
